version: '3.8'

services:
  nuxt-app:
    build: .
    container_name: nuxt-app
    networks:
      - foobar-revproxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nuxt-app.rule=Host(`trial.devops-ranch.in`)"
      - "traefik.http.services.nuxt-app.loadbalancer.server.port=3000"
    environment:
      - HOST=0.0.0.0
      - PORT=3000

  traefik:
    image: traefik:v2.5
    container_name: traefik
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.cloudflare.acme.dnschallenge=true"
      - "--certificatesresolvers.cloudflare.acme.dnschallenge.provider=cloudflare"
      - "--certificatesresolvers.cloudflare.acme.email=your-email@example.com"
      - "--certificatesresolvers.cloudflare.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./letsencrypt:/letsencrypt"
    environment:
      - CF_API_EMAIL=${version: '3.8'

services:
  nuxt-app:
    build: .
    container_name: nuxt-app
    networks:
      - foobar-revproxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nuxt-app.rule=Host(`trial.devops-ranch.in`)"
      - "traefik.http.services.nuxt-app.loadbalancer.server.port=3000"
    environment:
      - HOST=0.0.0.0
      - PORT=3000

  traefik:
    image: traefik:v2.5
    container_name: traefik
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.cloudflare.acme.dnschallenge=true"
      - "--certificatesresolvers.cloudflare.acme.dnschallenge.provider=cloudflare"
      - "--certificatesresolvers.cloudflare.acme.email=your-email@example.com"
      - "--certificatesresolvers.cloudflare.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./letsencrypt:/letsencrypt"
    environment:
      - CF_API_EMAIL=${CF_API_EMAIL}
      - CF_API_KEY=${CF_API_KEY}
    networks:
      - foobar-revproxy

networks:
  foobar-revproxy:
    driver: bridge
    name: foobar-revproxy
