version: '3.8'

services:
  nuxt-app:
    build: .
    container_name: nuxt-app
    networks:
      - foobar-revproxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nuxt-app.rule=Host(`trial.devops-ranch.in`)"

      - "traefik.http.services.nuxt-app.loadbalancer.server.port=3000"
    environment:
      - HOST=0.0.0.0
      - PORT=3000

  traefik:
    image: traefik:v2.5
    container_name: traefik
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - foobar-revproxy

networks:
  foobar-revproxy:
    driver: bridge
    name: foobar-revproxy
    
